apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - name: body
      description: request body i think
      type: string
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: /workspace/source
      command: ["/usr/bin/echo"]
      args:
        - "$(inputs.params.body)"
